package com.mattmc.mcptoolkit.ui.sample.client;

import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.ComponentPath;
import net.minecraft.client.gui.Font;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.AbstractWidget;
import net.minecraft.client.gui.components.ItemDisplayWidget;
import net.minecraft.client.gui.narration.NarrationElementOutput;
import net.minecraft.client.gui.navigation.FocusNavigationEvent;
import net.minecraft.client.gui.screens.inventory.InventoryScreen;
import net.minecraft.client.input.MouseButtonEvent;
import net.minecraft.client.renderer.RenderPipelines;
import net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer;
import net.minecraft.client.renderer.entity.state.ArmorStandRenderState;
import net.minecraft.client.renderer.entity.state.EntityRenderState;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;
import net.minecraft.client.renderer.item.ItemModelResolver;
import net.minecraft.client.sounds.SoundManager;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.locale.Language;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.FormattedText;
import net.minecraft.resources.Identifier;
import net.minecraft.util.Mth;
import net.minecraft.util.Util;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntitySpawnReason;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.EntityTypes;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.inventory.AbstractContainerMenu;
import net.minecraft.world.inventory.Slot;
import net.minecraft.world.item.ItemDisplayContext;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.equipment.Equippable;
import org.joml.Quaternionf;
import org.joml.Vector3f;

import java.util.List;
import java.util.function.Supplier;

/**
 * GENERATED by the mcp-toolkit screen compiler (format 1) - DO NOT EDIT. Regenerated
 * whenever any screen of this mod is; identical for every screen, one copy per mod.
 *
 * <p>The widgets and paint primitives every generated {@code <Screen>Layout} in this mod is built
 * from. Vendored on purpose: this mod depends on nobody for its screens, so the ~200 lines a
 * library would have exported live here instead (SCREEN_AUTHORING_DESIGN.md section 7). The bodies
 * are the same source the toolkit's dev-time interpreter draws with, which is what makes the
 * interpreted preview and this shipped code paint the same pixels.
 *
 * <p>Every widget carries its document element's {@code id} and {@code kind} ({@link Declared}),
 * so a tool reading the widget tree - the toolkit's {@code get_screen}, {@code click} - can name
 * it. Decoration is a real, inactive widget for the same reason: a panel painted from
 * {@code render()} is invisible to every tool.
 */
@Environment(EnvType.CLIENT)
public final class McptoolkitUi {
    private McptoolkitUi() {}

    /** A widget that came from a document element, and says which. */
    public interface Declared {
        /** The element's declared id, or {@code null} for an unnamed element. */
        String uiId();

        /** The element's kind, by its document name ({@code "label"}, {@code "bar"}, ...). */
        String uiKind();
    }

    /** The four text variants of a {@code label} element. */
    public enum LabelMode {
        PLAIN, WRAPPED, SCROLLING, TRUNCATED
    }

    /** {@code value / max} for a bar, with a zero denominator guarded (section 8.2). */
    public static float fraction(final int value, final int max) {
        return max <= 0 ? 0.0F : value / (float) max;
    }

    /** An item stack by id for an {@code item} element; an unknown id shows a barrier. */
    public static ItemStack stack(final String id, final int count) {
        Identifier rl = Identifier.tryParse(id);
        Item item = rl == null ? null : BuiltInRegistries.ITEM.getOptional(rl).orElse(null);
        return new ItemStack(item == null ? Items.BARRIER : item, count);
    }

    // ---------------------------------------------------------------------------------------------

    /**
     * The {@code label} element: text in one of four modes, drawn with an explicit colour and shadow
     * because in 26.2 no vanilla string widget draws a container label (0xFF404040, no shadow).
     */
    public static final class Label extends AbstractWidget implements Declared {
        /** Vanilla's line height. */
        public static final int LINE_HEIGHT = 9;
        private static final String ELLIPSIS = "...";

        private final String id;
        private final Font font;
        private final LabelMode mode;
        private final int color;
        private final boolean shadow;

        public Label(final String id, final int x, final int y, final int w, final int h,
                     final Component text, final Font font, final LabelMode mode, final int color, final boolean shadow) {
            super(x, y, w > 0 ? w : font.width(text), h > 0 ? h : naturalHeight(font, text, w, mode), text);
            this.id = id;
            this.font = font;
            this.mode = mode;
            this.color = color;
            this.shadow = shadow;
            this.active = false;
        }

        private static int naturalHeight(final Font font, final Component text, final int w, final LabelMode mode) {
            if (mode == LabelMode.WRAPPED && w > 0) {
                return Math.max(1, font.split(text, w).size()) * LINE_HEIGHT;
            }
            return LINE_HEIGHT;
        }

        @Override
        public String uiId() {
            return id;
        }

        @Override
        public String uiKind() {
            return "label";
        }

        @Override
        protected void extractWidgetRenderState(final GuiGraphicsExtractor g, final int mouseX, final int mouseY, final float a) {
            Component text = getMessage();
            int x = getX();
            int w = getWidth();
            int h = getHeight();
            // A one-line label in a box taller than a line sits where vanilla's scrolling helper would
            // put it; a natural-height label sits at its y.
            int lineY = h > LINE_HEIGHT ? (getY() + getY() + h - LINE_HEIGHT) / 2 + 1 : getY();
            switch (mode) {
                case PLAIN -> g.text(font, text, x, lineY, color, shadow);
                case WRAPPED -> g.textWithWordWrap(font, text, x, getY(), w, color, shadow);
                case TRUNCATED -> {
                    if (font.width(text) <= w) {
                        g.text(font, text, x, lineY, color, shadow);
                    } else {
                        FormattedText cut = font.substrByWidth(text, Math.max(0, w - font.width(ELLIPSIS)));
                        g.text(font, Language.getInstance().getVisualOrder(cut), x, lineY, color, shadow);
                        g.text(font, ELLIPSIS, x + font.width(cut), lineY, color, shadow);
                    }
                }
                case SCROLLING -> {
                    int lineWidth = font.width(text);
                    if (lineWidth <= w) {
                        g.text(font, text, x, lineY, color, shadow);
                    } else {
                        // Vanilla's defaultScrollingHelper, verbatim, so every scrolling string on a screen
                        // breathes at the same rate.
                        int maxPosition = lineWidth - w;
                        double time = Util.getMillis() / 1000.0;
                        double period = Math.max(maxPosition * 0.5, 3.0);
                        double alpha = Math.sin((Math.PI / 2) * Math.cos((Math.PI * 2) * time / period)) / 2.0 + 0.5;
                        double pos = Mth.lerp(alpha, 0.0, maxPosition);
                        g.enableScissor(x, getY(), x + w, getY() + h);
                        g.text(font, text, x - (int) pos, lineY, color, shadow);
                        g.disableScissor();
                    }
                }
            }
        }

        @Override
        protected void updateWidgetNarration(final NarrationElementOutput output) {
            // Static text narrates as part of the screen, not as a focusable element.
        }

        @Override
        public ComponentPath nextFocusPath(final FocusNavigationEvent navigationEvent) {
            return null;
        }

        @Override
        public void playDownSound(final SoundManager soundManager) {
            // Silent.
        }
    }

    /**
     * A decorative element as a real, inactive widget: panels, wells, frames, bars, regions and
     * layout nodes. Inactive, so a panel under a button never takes the click.
     */
    public static final class Decor extends AbstractWidget implements Declared {
        /** How to paint this rectangle, in absolute coordinates. */
        @FunctionalInterface
        public interface Painter {
            void paint(GuiGraphicsExtractor g, int x, int y, int w, int h, int mouseX, int mouseY, float partialTick);
        }

        private final String id;
        private final String kind;
        private final Painter painter;

        public Decor(final String id, final String kind, final int x, final int y, final int w, final int h,
                     final Painter painter) {
            super(x, y, w, h, Component.empty()); // the id rides Declared, not the message
            this.id = id;
            this.kind = kind;
            this.painter = painter;
            this.active = false;
        }

        @Override
        public String uiId() {
            return id;
        }

        @Override
        public String uiKind() {
            return kind;
        }

        @Override
        protected void extractWidgetRenderState(final GuiGraphicsExtractor graphics, final int mouseX, final int mouseY, final float partialTick) {
            painter.paint(graphics, getX(), getY(), getWidth(), getHeight(), mouseX, mouseY, partialTick);
        }

        @Override
        protected void updateWidgetNarration(final NarrationElementOutput output) {
            // Decoration narrates nothing.
        }

        @Override
        public ComponentPath nextFocusPath(final FocusNavigationEvent navigationEvent) {
            return null; // never in the tab order
        }

        @Override
        public void playDownSound(final SoundManager soundManager) {
            // Silent: nothing was pressed.
        }
    }

    /**
     * A button bound to a declared action; with a sprite, the sprite is drawn over the face.
     *
     * <p>{@code bare} is the document's {@code face: none}: there IS no face, the sprite fills the
     * button, a hover sprite replaces it under the pointer, and an inactive button draws at half
     * alpha.
     */
    public static final class PressButton extends net.minecraft.client.gui.components.Button.Plain implements Declared {
        private final String id;
        private final Identifier sprite;
        private final Identifier spriteHovered;
        private final boolean bare;

        public PressButton(final String id, final int x, final int y, final int w, final int h,
                           final Component text, final Identifier sprite, final Identifier spriteHovered,
                           final boolean bare, final OnPress onPress) {
            super(x, y, w, h, text, onPress, DEFAULT_NARRATION);
            this.id = id;
            this.sprite = sprite;
            this.spriteHovered = spriteHovered;
            this.bare = bare;
        }

        @Override
        public String uiId() {
            return id;
        }

        @Override
        public String uiKind() {
            return "button";
        }

        @Override
        protected void extractContents(final GuiGraphicsExtractor graphics, final int mouseX, final int mouseY, final float a) {
            if (!bare) {
                super.extractContents(graphics, mouseX, mouseY, a);
            }
            Identifier drawn = isHovered() && spriteHovered != null ? spriteHovered : sprite;
            if (drawn == null) {
                return;
            }
            int sx;
            int sy;
            int sw;
            int sh;
            if (bare) {
                // No face to sit on: the sprite IS the button.
                sx = getX();
                sy = getY();
                sw = getWidth();
                sh = getHeight();
            } else {
                // A square inset by the face's 2px border on each side, centred: a 20x20 button
                // shows a 16x16 sprite, vanilla's icon size.
                int size = Math.max(1, Math.min(getWidth(), getHeight()) - 4);
                sx = getX() + (getWidth() - size) / 2;
                sy = getY() + (getHeight() - size) / 2;
                sw = size;
                sh = size;
            }
            graphics.blitSprite(RenderPipelines.GUI_TEXTURED, drawn, sx, sy, sw, sh, active ? -1 : 0x80FFFFFF);
        }
    }

    /**
     * A GUI-atlas sprite, or a window into a raw texture at any scale. Inactive and unfocusable.
     *
     * <p>The texture form is one vanilla blit with a source rectangle and a destination rectangle,
     * which is cropping, scaling and tinting in a single call.
     */
    public static final class Icon extends AbstractWidget implements Declared {
        private final String id;
        private final Identifier sprite;
        private final Identifier texture;
        private final int u;
        private final int v;
        private final int srcW;
        private final int srcH;
        private final int sheetW;
        private final int sheetH;
        private final int color;

        public Icon(final String id, final int x, final int y, final int w, final int h,
                    final Identifier sprite, final Identifier texture, final int u, final int v,
                    final int srcW, final int srcH, final int sheetW, final int sheetH, final int color) {
            super(x, y, w, h, Component.empty());
            this.id = id;
            this.sprite = sprite;
            this.texture = texture;
            this.u = u;
            this.v = v;
            this.srcW = srcW;
            this.srcH = srcH;
            this.sheetW = sheetW;
            this.sheetH = sheetH;
            this.color = color;
            this.active = false;
        }

        @Override
        public String uiId() {
            return id;
        }

        @Override
        public String uiKind() {
            return "icon";
        }

        @Override
        protected void extractWidgetRenderState(final GuiGraphicsExtractor graphics, final int mouseX, final int mouseY, final float a) {
            if (sprite != null) {
                graphics.blitSprite(RenderPipelines.GUI_TEXTURED, sprite, getX(), getY(), getWidth(), getHeight(), color);
            } else if (texture != null) {
                graphics.blit(RenderPipelines.GUI_TEXTURED, texture, getX(), getY(), u, v,
                    getWidth(), getHeight(), srcW, srcH, sheetW, sheetH, color);
            }
        }

        @Override
        protected void updateWidgetNarration(final NarrationElementOutput output) {
            // An icon narrates nothing.
        }

        @Override
        public ComponentPath nextFocusPath(final FocusNavigationEvent navigationEvent) {
            return null;
        }

        @Override
        public void playDownSound(final SoundManager soundManager) {
            // Silent.
        }
    }

    /**
     * A live entity in a rectangle: the player, an armour stand wearing what named slots hold, or any
     * entity type.
     *
     * <p>{@code GuiGraphicsExtractor.entity} is one call; what surrounds it - building a render state,
     * driving the right renderer, the two rotations, the drag - is identical in every screen that
     * does this, which is why it is here rather than in a hook.
     */
    public static final class EntityView extends AbstractWidget implements Declared {
        /** Vanilla's own inventory offset: it lifts the subject so its feet sit on the bottom edge. */
        private static final float FOOT_OFFSET = 0.0625F;
        /** An armour stand's real hitbox, so the translation below centres it as vanilla does. */
        private static final float STAND_WIDTH = 0.5F;
        private static final float STAND_HEIGHT = 1.975F;

        private final String id;
        private final String subject;
        private final float scale;
        private final float pitch;
        private final float yaw;
        private final boolean followMouse;
        private final Supplier<List<ItemStack>> equipment;
        private final ArmorStandRenderState stand = new ArmorStandRenderState();
        private Entity created;
        private boolean createTried;
        private float dragYaw;

        public EntityView(final String id, final int x, final int y, final int w, final int h,
                          final String subject, final float scale, final float pitch, final float yaw,
                          final boolean followMouse, final boolean draggable,
                          final Supplier<List<ItemStack>> equipment) {
            super(x, y, w, h, Component.empty());
            this.id = id;
            this.subject = subject;
            this.scale = scale;
            this.pitch = pitch;
            this.yaw = yaw;
            this.followMouse = followMouse;
            this.equipment = equipment;
            // Active ONLY when it can be turned: an inactive widget takes no click, so a preview
            // never steals one from the slot behind it.
            this.active = draggable;
            this.stand.entityType = EntityTypes.ARMOR_STAND;
            this.stand.showBasePlate = false;
            this.stand.showArms = true;
            this.stand.boundingBoxWidth = STAND_WIDTH;
            this.stand.boundingBoxHeight = STAND_HEIGHT;
        }

        @Override
        public String uiId() {
            return id;
        }

        @Override
        public String uiKind() {
            return "entity";
        }

        @Override
        protected void onDrag(final MouseButtonEvent event, final double dx, final double dy) {
            dragYaw += (float) dx;
        }

        @Override
        protected void extractWidgetRenderState(final GuiGraphicsExtractor graphics, final int mouseX, final int mouseY, final float a) {
            Minecraft mc = Minecraft.getInstance();
            int x0 = getX();
            int y0 = getY();
            int x1 = x0 + getWidth();
            int y1 = y0 + getHeight();
            LivingEntity live = livingSubject(mc);
            if (live != null && followMouse && dragYaw == 0.0F) {
                // Vanilla's own helper, verbatim: the inventory's subject looks at the pointer, and
                // reimplementing that is how two screens come to breathe at different rates.
                InventoryScreen.extractEntityInInventoryFollowsMouse(graphics, x0, y0, x1, y1,
                    (int) scale, FOOT_OFFSET, mouseX, mouseY, live);
                return;
            }
            EntityRenderState state = renderState(mc, live);
            if (state == null) {
                return;
            }
            float turn = yaw + dragYaw;
            if (state instanceof LivingEntityRenderState living) {
                living.bodyRot = 180.0F + turn;
                living.yRot = turn;
                living.xRot = pitch;
            }
            Quaternionf rotation = new Quaternionf()
                .rotationXYZ(pitch * ((float) Math.PI / 180.0F), 0.0F, (float) Math.PI);
            Vector3f translation = new Vector3f(0.0F, state.boundingBoxHeight / 2.0F + FOOT_OFFSET, 0.0F);
            graphics.entity(state, scale, translation, rotation, null, x0, y0, x1, y1);
        }

        /** The subject as a living entity, when there is one: the player, or a created mob. */
        private LivingEntity livingSubject(final Minecraft mc) {
            if ("player".equals(subject)) {
                return mc.player;
            }
            if ("armor_stand".equals(subject)) {
                return null;
            }
            return subjectEntity(mc) instanceof LivingEntity living ? living : null;
        }

        /** The render state to draw: the armour stand's own, or the dispatcher's for a real entity. */
        private EntityRenderState renderState(final Minecraft mc, final LivingEntity live) {
            if ("armor_stand".equals(subject)) {
                equip();
                return stand;
            }
            Entity entity = live != null ? live : subjectEntity(mc);
            if (entity == null) {
                return null;
            }
            EntityRenderState state = mc.getEntityRenderDispatcher().getRenderer(entity).createRenderState(entity, 1.0F);
            state.shadowPieces.clear();
            state.shadowRadius = 0.0F;
            return state;
        }

        /**
         * The entity behind an entity-type subject: created once against the client level and never
         * added to it, so it ticks nothing and nobody can see it but this rectangle.
         */
        private Entity subjectEntity(final Minecraft mc) {
            if (createTried || mc.level == null) {
                return created;
            }
            createTried = true;
            Identifier rl = Identifier.tryParse(subject);
            EntityType<?> type = rl == null ? null : BuiltInRegistries.ENTITY_TYPE.getOptional(rl).orElse(null);
            created = type == null ? null : type.create(mc.level, EntitySpawnReason.LOAD);
            return created;
        }

        /**
         * Dress the armour stand in whatever the named slots hold - vanilla's own routing, which is
         * what a screen that shows an armour SET is for.
         */
        private void equip() {
            stand.headEquipment = ItemStack.EMPTY;
            stand.chestEquipment = ItemStack.EMPTY;
            stand.legsEquipment = ItemStack.EMPTY;
            stand.feetEquipment = ItemStack.EMPTY;
            stand.leftHandItemStack = ItemStack.EMPTY;
            stand.leftHandItemState.clear();
            stand.headItem.clear();
            ItemModelResolver resolver = Minecraft.getInstance().getItemModelResolver();
            for (ItemStack stack : equipment.get()) {
                if (stack.isEmpty()) {
                    continue;
                }
                Equippable equippable = stack.get(DataComponents.EQUIPPABLE);
                EquipmentSlot slot = equippable == null ? null : equippable.slot();
                if (slot == EquipmentSlot.HEAD) {
                    if (HumanoidArmorLayer.shouldRender(stack, EquipmentSlot.HEAD)) {
                        stand.headEquipment = stack.copy();
                    } else {
                        resolver.updateForTopItem(stand.headItem, stack, ItemDisplayContext.HEAD, null, null, 0);
                    }
                } else if (slot == EquipmentSlot.CHEST) {
                    stand.chestEquipment = stack.copy();
                } else if (slot == EquipmentSlot.LEGS) {
                    stand.legsEquipment = stack.copy();
                } else if (slot == EquipmentSlot.FEET) {
                    stand.feetEquipment = stack.copy();
                } else {
                    stand.leftHandItemStack = stack.copy();
                    resolver.updateForTopItem(stand.leftHandItemState, stack,
                        ItemDisplayContext.THIRD_PERSON_LEFT_HAND, null, null, 0);
                }
            }
        }

        @Override
        protected void updateWidgetNarration(final NarrationElementOutput output) {
            // A preview narrates nothing.
        }

        @Override
        public ComponentPath nextFocusPath(final FocusNavigationEvent navigationEvent) {
            return null;
        }

        @Override
        public void playDownSound(final SoundManager soundManager) {
            // Silent: turning a preview is not pressing anything.
        }
    }

    /** A static item display, tooltip on hover. ({@code ItemView}, because {@code Item} is vanilla's.) */
    public static final class ItemView extends ItemDisplayWidget implements Declared {
        private final String id;

        public ItemView(final String id, final int x, final int y, final ItemStack stack, final boolean decorated) {
            super(Minecraft.getInstance(), 0, 0, 16, 16, Component.empty(), stack, decorated, true);
            this.id = id;
            setX(x);
            setY(y);
        }

        @Override
        public String uiId() {
            return id;
        }

        @Override
        public String uiKind() {
            return "item";
        }
    }

    // ---------------------------------------------------------------------------------------------

    /** The texture-less drawing primitives: vanilla's container grey, lit from the top-left. */
    public static final class Paint {
        /** Vanilla's own slot background. The one sprite a texture-less container screen still needs. */
        public static final Identifier SLOT_SPRITE = Identifier.withDefaultNamespace("container/slot");

        private Paint() {}

        /** A raised panel. The edge fills overlap at the corners and the dark edges win there. */
        public static void panel(final GuiGraphicsExtractor g, final int x, final int y, final int w, final int h) {
            g.fill(x, y, x + w, y + h, 0xFFC6C6C6);
            g.fill(x, y, x + w, y + 1, 0xFFFFFFFF);
            g.fill(x, y, x + 1, y + h, 0xFFFFFFFF);
            g.fill(x, y + h - 1, x + w, y + h, 0xFF555555);
            g.fill(x + w - 1, y, x + w, y + h, 0xFF555555);
        }

        /** A recessed well: only the top and left edges, and they are the dark colour. */
        public static void well(final GuiGraphicsExtractor g, final int x, final int y, final int w, final int h) {
            g.fill(x, y, x + w, y + h, 0xFF8B8B8B);
            g.fill(x, y, x + w, y + 1, 0xFF555555);
            g.fill(x, y, x + 1, y + h, 0xFF555555);
        }

        /** The outer border of a texture-less screen: a dark frame with the panel grey inset by one pixel. */
        public static void screenFrame(final GuiGraphicsExtractor g, final int x, final int y, final int w, final int h) {
            g.fill(x, y, x + w, y + h, 0xFF373737);
            g.fill(x + 1, y + 1, x + w - 1, y + h - 1, 0xFFC6C6C6);
        }

        /** A horizontal fill-proportion bar, framed, with a track behind the fill. */
        public static void bar(final GuiGraphicsExtractor g, final int x, final int y, final int w, final int h,
                               final float frac, final int fg, final int track) {
            g.fill(x, y, x + w, y + h, 0xFF202020);
            g.fill(x + 1, y + 1, x + w - 1, y + h - 1, track);
            int filled = (int) ((w - 2) * Mth.clamp(frac, 0.0F, 1.0F));
            if (filled > 0) {
                g.fill(x + 1, y + 1, x + 1 + filled, y + h - 1, fg);
            }
        }

        /** The same bar stood on end and filling upward. */
        public static void barVertical(final GuiGraphicsExtractor g, final int x, final int y, final int w, final int h,
                                       final float frac, final int fg, final int track) {
            g.fill(x, y, x + w, y + h, 0xFF202020);
            g.fill(x + 1, y + 1, x + w - 1, y + h - 1, track);
            int filled = (int) ((h - 2) * Mth.clamp(frac, 0.0F, 1.0F));
            if (filled > 0) {
                g.fill(x + 1, y + h - 1 - filled, x + w - 1, y + h - 1, fg);
            }
        }

        /** Vanilla's slot background under every active slot of a menu. Pass 0, 0 when the pose is at the panel origin. */
        public static void slots(final GuiGraphicsExtractor g, final AbstractContainerMenu menu,
                                 final int leftPos, final int topPos) {
            for (Slot slot : menu.slots) {
                if (slot.isActive()) {
                    g.blitSprite(RenderPipelines.GUI_TEXTURED, SLOT_SPRITE,
                        leftPos + slot.x - 1, topPos + slot.y - 1, 18, 18);
                }
            }
        }

        /** A widget that shows a tooltip, and what to show. The lines are a supplier: most are dynamic. */
        public record Hover(AbstractWidget widget, Supplier<List<Component>> lines) {}

        /** The first tooltip zone under the pointer, drawn. One loop, one rule, both renderers. */
        public static void tooltips(final GuiGraphicsExtractor g, final Font font, final List<Hover> zones,
                                    final int mouseX, final int mouseY) {
            for (Hover h : zones) {
                AbstractWidget w = h.widget();
                if (!w.visible || mouseX < w.getX() || mouseY < w.getY()
                    || mouseX >= w.getX() + w.getWidth() || mouseY >= w.getY() + w.getHeight()) {
                    continue;
                }
                List<Component> lines = h.lines().get();
                if (lines == null || lines.isEmpty()) {
                    continue;
                }
                g.setComponentTooltipForNextFrame(font, lines, mouseX, mouseY);
                return;
            }
        }
    }
}
