// docs/platform/HEADLESS.md, generated: which tools answer with no client attached (RELEASE_1.md
// section K1, ArmorPieces' ask 2). The source is the bridge's own `context` column on GET /tools -
// every ToolDef's ExecutionContext, lower-cased - so the document is a statement the registry
// made, not one a person remembered. `node tools/headless-doc.mjs` from mcp-toolkit/ reads a live
// bridge (MCPTK_URL, default the dev port) or `--from <manifest.json>` (a probes/fixtures capture)
// and rewrites the file; probes/headless-surface.test.mjs checks the table back against a live
// manifest, so a tool added without regenerating fails a probe rather than drifting.
//
// Capture from a CLIENT: a dedicated server never registers the client tools at all, so a table
// generated from one would be honest but would not name what a client adds. The table carries
// every toolkit-owned tool; extension tools (`source` set) come and go with the mods loaded and
// are listed separately with their mod named.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "docs", "platform", "HEADLESS.md");
const BASE = process.env.MCPTK_URL || "http://127.0.0.1:25599";

async function manifest() {
  const i = process.argv.indexOf("--from");
  if (i >= 0) return JSON.parse(readFileSync(process.argv[i + 1], "utf8"));
  const res = await fetch(`${BASE}/tools`, { signal: AbortSignal.timeout(5000) });
  if (!res.ok) throw new Error(`GET ${BASE}/tools: HTTP ${res.status}`);
  return res.json();
}

const ORDER = { server: 0, any: 1, client: 2 };
const WHERE = {
  server: "a loaded world, on either process",
  any: "the bridge alone - before a world, and on a dedicated server",
  client: "a game client; never present headless",
};

export function render(tools, { source = "a live bridge", when = new Date() } = {}) {
  const missing = tools.filter((t) => typeof t.context !== "string");
  if (missing.length) {
    throw new Error(`${missing.length} tool(s) carry no context column (bridge older than 0.129.0?): ${missing.map((t) => t.name).join(", ")}`);
  }
  const own = tools.filter((t) => !t.source);
  const ext = tools.filter((t) => t.source);
  const sorted = (xs) => [...xs].sort((a, b) => (ORDER[a.context] - ORDER[b.context]) || a.name.localeCompare(b.name));
  const counts = { server: 0, any: 0, client: 0 };
  for (const t of own) counts[t.context] = (counts[t.context] ?? 0) + 1;
  const row = (t) => `| \`${t.name}\` | ${t.context} | ${t.mechanism ?? ""} |`;
  const lines = [];
  lines.push("# Which tools answer without a client");
  lines.push("");
  lines.push("GENERATED by `tools/headless-doc.mjs` from the bridge's `GET /tools` manifest - do not edit by");
  lines.push(`hand; regenerate. Captured from ${source} on ${when.toISOString().slice(0, 10)}.`);
  lines.push("");
  lines.push("Every tool declares an execution context (`ExecutionContext` in the toolkit, served as the manifest's");
  lines.push("`context` column since 0.129.0). A suite that drives a DEDICATED SERVER - no client, no screen - can");
  lines.push("be written against this table rather than discovered by trying:");
  lines.push("");
  lines.push("| Context | Answers on | Toolkit tools |");
  lines.push("|---|---|---|");
  for (const c of ["server", "any", "client"]) lines.push(`| \`${c}\` | ${WHERE[c]} | ${counts[c]} |`);
  lines.push("");
  lines.push("What the contexts mean, mechanically (`BridgeServer.dispatch`):");
  lines.push("");
  lines.push("- **`server`** runs on the server thread and refuses with `no server running` until a world is loaded.");
  lines.push("  On a dedicated server that is from boot; on a client, once a world is open.");
  lines.push("- **`any`** runs inline on the bridge's own thread with no world needed - `ping`, the log, the launcher.");
  lines.push("- **`client`** runs on the render thread. A dedicated server never REGISTERS these, so they are absent");
  lines.push("  from its manifest rather than present and refusing; the MCP shim hides the same set from every");
  lines.push("  headless role (`CLIENT_SURFACE` in `index.mjs`, which this column checks on every fetch).");
  lines.push("");
  lines.push("`ping` reports `clientPresent` and `serverRunning` for the live answer; this table is the promise.");
  lines.push("");
  lines.push("## Toolkit tools");
  lines.push("");
  lines.push("| Tool | Context | Mechanism |");
  lines.push("|---|---|---|");
  for (const t of sorted(own)) lines.push(row(t));
  if (ext.length) {
    lines.push("");
    lines.push("## Extension tools in this capture");
    lines.push("");
    lines.push("Present only when the mod that registers them is loaded; listed for the record of this capture.");
    lines.push("");
    lines.push("| Tool | Context | Mechanism | Mod |");
    lines.push("|---|---|---|---|");
    for (const t of sorted(ext)) lines.push(`${row(t).slice(0, -2)} | \`${t.source}\` |`);
  }
  lines.push("");
  return lines.join("\n");
}

/** The table back out of the document: name -> context, toolkit rows only. */
export function parseTable(md) {
  const out = new Map();
  const section = md.split("## Toolkit tools")[1]?.split("## Extension tools")[0] ?? "";
  for (const line of section.split("\n")) {
    const m = /^\| `([^`]+)` \| (server|any|client) \|/.exec(line);
    if (m) out.set(m[1], m[2]);
  }
  return out;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const tools = await manifest();
  const i = process.argv.indexOf("--from");
  const source = i >= 0 ? `\`${process.argv[i + 1].replace(/\\/g, "/").split("/").slice(-2).join("/")}\`` : `a live bridge at ${BASE}`;
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, render(tools, { source }), "utf8");
  console.log(`wrote ${OUT}: ${tools.length} tools`);
}
