{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mattmc.gradle",
    "module": "gradle-conventions",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-conventions-0.7.0.jar",
          "url": "gradle-conventions-0.7.0.jar",
          "size": 118346,
          "sha512": "f6611b5507b68bd330cdc13a0e90fc1d05cd3667348a32adc92f71f9a59eb7d33c3692470ffe346d27c59c0195cf69a38dce78173876e32af820a4ed2ae59fd2",
          "sha256": "5529c34035f894938912a8877ff079fecc90d40951066148ce717bd08a43b845",
          "sha1": "6f553c77401af1e784251d301e0a14a4b5022b74",
          "md5": "508a687bce44472f1265dabf6748ab39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-conventions-0.7.0.jar",
          "url": "gradle-conventions-0.7.0.jar",
          "size": 118346,
          "sha512": "f6611b5507b68bd330cdc13a0e90fc1d05cd3667348a32adc92f71f9a59eb7d33c3692470ffe346d27c59c0195cf69a38dce78173876e32af820a4ed2ae59fd2",
          "sha256": "5529c34035f894938912a8877ff079fecc90d40951066148ce717bd08a43b845",
          "sha1": "6f553c77401af1e784251d301e0a14a4b5022b74",
          "md5": "508a687bce44472f1265dabf6748ab39"
        }
      ]
    }
  ]
}
